In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
!pip install BERTopic

Requirement already satisfied: BERTopic in /usr/local/lib/python3.10/dist-packages (0.16.4)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.10/dist-packages (from BERTopic) (0.8.40)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.10/dist-packages (from BERTopic) (1.26.4)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.10/dist-packages (from BERTopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.10/dist-packages (from BERTopic) (5.24.1)
Requirement already satisfied: scikit-learn>=0.22.2.post1 in /usr/local/lib/python3.10/dist-packages (from BERTopic) (1.5.2)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from BERTopic) (3.2.1)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.10/dist-packages (from BERTopic) (4.66.6)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.10/dist-packages (from BERTopic) (0.5.7)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.10/dist-packages (from hdbscan>=0.8.29->BERTopic) (1.13.1)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.10/dist-packages (from hdbscan>=0.8.29->BERTopic) (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.5->BERTopic) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.5->BERTopic) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.5->BERTopic) (2024.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly>=4.7.0->BERTopic) (9.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from plotly>=4.7.0->BERTopic) (24.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.22.2.post1->BERTopic) (3.5.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->BERTopic) (4.46.3)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->BERTopic) (2.5.1+cu121)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->BERTopic) (0.26.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->BERTopic) (11.0.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.10/dist-packages (from umap-learn>=0.5.0->BERTopic) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.10/dist-packages (from umap-learn>=0.5.0->BERTopic) (0.5.13)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->BERTopic) (3.16.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->BERTopic) (2024.10.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->BERTopic) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->BERTopic) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->BERTopic) (4.12.2)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba>=0.51.2->umap-learn>=0.5.0->BERTopic) (0.43.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->BERTopic) (1.16.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->BERTopic) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->BERTopic) (3.1.4)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->BERTopic) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers>=0.4.1->BERTopic) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->BERTopic) (2024.9.11)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->BERTopic) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->BERTopic) (0.4.5)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->BERTopic) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->BERTopic) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->BERTopic) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->BERTopic) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->BERTopic) (2024.8.30)

In [3]:
!pip install bertopic
!pip install --upgrade joblib==1.1.0 # HDBScan fails to load with joblib==1.2.0
!pip install --upgrade git+https://github.com/scikit-learn-contrib/hdbscan.git#egg=hdbscan

Requirement already satisfied: bertopic in /usr/local/lib/python3.10/dist-packages (0.16.4)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.10/dist-packages (from bertopic) (0.8.40)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.10/dist-packages (from bertopic) (1.26.4)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.10/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.10/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=0.22.2.post1 in /usr/local/lib/python3.10/dist-packages (from bertopic) (1.5.2)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from bertopic) (3.2.1)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.10/dist-packages (from bertopic) (4.66.6)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.10/dist-packages (from bertopic) (0.5.7)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.10/dist-packages (from hdbscan>=0.8.29->bertopic) (1.13.1)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.10/dist-packages (from hdbscan>=0.8.29->bertopic) (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.5->bertopic) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.5->bertopic) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.5->bertopic) (2024.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly>=4.7.0->bertopic) (9.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from plotly>=4.7.0->bertopic) (24.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.22.2.post1->bertopic) (3.5.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.46.3)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.5.1+cu121)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->bertopic) (0.26.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->bertopic) (11.0.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.10/dist-packages (from umap-learn>=0.5.0->bertopic) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.10/dist-packages (from umap-learn>=0.5.0->bertopic) (0.5.13)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.16.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2024.10.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (4.12.2)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba>=0.51.2->umap-learn>=0.5.0->bertopic) (0.43.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.16.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.4)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2024.9.11)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.4.5)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2024.8.30)
Collecting joblib==1.1.0
  Using cached joblib-1.1.0-py2.py3-none-any.whl.metadata (5.2 kB)
Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Installing collected packages: joblib
  Attempting uninstall: joblib
    Found existing installation: joblib 1.4.2
    Uninstalling joblib-1.4.2:
      Successfully uninstalled joblib-1.4.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imbalanced-learn 0.12.4 requires joblib>=1.1.1, but you have joblib 1.1.0 which is incompatible.
scikit-learn 1.5.2 requires joblib>=1.2.0, but you have joblib 1.1.0 which is incompatible.
Successfully installed joblib-1.1.0
Collecting hdbscan
  Cloning https://github.com/scikit-learn-contrib/hdbscan.git to /tmp/pip-install-q5te_7hy/hdbscan_69b21eea27eb4512a34ae2e2b270019e
  Running command git clone --filter=blob:none --quiet https://github.com/scikit-learn-contrib/hdbscan.git /tmp/pip-install-q5te_7hy/hdbscan_69b21eea27eb4512a34ae2e2b270019e
  Resolved https://github.com/scikit-learn-contrib/hdbscan.git to commit f0285287a62084e3a796f3a34901181972966b72
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy<3,>=1.20 in /usr/local/lib/python3.10/dist-packages (from hdbscan) (1.26.4)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.10/dist-packages (from hdbscan) (1.13.1)
Requirement already satisfied: scikit-learn>=0.20 in /usr/local/lib/python3.10/dist-packages (from hdbscan) (1.5.2)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.10/dist-packages (from hdbscan) (1.1.0)
Collecting joblib>=1.0 (from hdbscan)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20->hdbscan) (3.5.0)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Installing collected packages: joblib
  Attempting uninstall: joblib
    Found existing installation: joblib 1.1.0
    Uninstalling joblib-1.1.0:
      Successfully uninstalled joblib-1.1.0
Successfully installed joblib-1.4.2

In [4]:

import os
import pandas as pd
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer
from umap import UMAP # In case we want to make results deterministic and reproducible

In [5]:
with open("drive/MyDrive/stopwords.txt", 'r', encoding="utf8") as f:
    stop = f.read().splitlines()

vectorizer_model = CountVectorizer(ngram_range=(1, 1), stop_words=frozenset(stop))

In [6]:
# Prepare data
df = pd.read_csv('drive/MyDrive/preprocessed_lenta_titles.csv', encoding="utf-8")
df['text_lemm'].dropna(inplace=True)
docs = df['text_ready'].astype(str).values.tolist()

In [7]:
df.head()

,Unnamed: 0,title,tags,text_lower,text_punct,text_stop,text_common,text_rare,text_nonum,text_token,text_lemm,text_ready
0,0,В Курской области объявили опасность атаки БПЛА,Происшествия,в курской области объявили опасность атаки бпла,в курской области объявили опасность атаки бпла,курской области объявили опасность атаки бпла,курской объявили опасность атаки бпла,курской объявили опасность атаки бпла,курской объявили опасность атаки бпла,"['курской', 'объявили', 'опасность', 'атаки', ...",курский объявить опасность атака бпнуть,курский область объявить опасность атака бпнуть
1,1,Юристы прокомментировали иск пострадавших в от...,Следствие и суд,юристы прокомментировали иск пострадавших в от...,юристы прокомментировали иск пострадавших в от...,юристы прокомментировали иск пострадавших отно...,юристы прокомментировали иск пострадавших отно...,юристы прокомментировали иск пострадавших отно...,юристы прокомментировали иск пострадавших отно...,"['юристы', 'прокомментировали', 'иск', 'постра...",юрист прокомментировать иск пострадать отношен...,юрист прокомментировать иск пострадать отношен...
2,2,На Западе рассказали о нехватке Patriot для пе...,Политика,на западе рассказали о нехватке patriot для пе...,на западе рассказали о нехватке patriot для пе...,западе рассказали нехватке patriot передачи всу,западе нехватке patriot передачи,западе нехватке patriot передачи,западе нехватке patriot передачи,"['западе', 'нехватке', 'patriot', 'передачи']",запад нехватка patriot передача,запад рассказать нехватка patriot передача всу
3,3,Очередные российские спортсмены отказались от ...,Летние виды,очередные российские спортсмены отказались от ...,очередные российские спортсмены отказались от ...,очередные российские спортсмены отказались уча...,очередные спортсмены отказались участия олимпиаде,очередные спортсмены отказались участия олимпиаде,очередные спортсмены отказались участия олимпиаде,"['очередные', 'спортсмены', 'отказались', 'уча...",очередной спортсмен отказаться участие олимпиада,очередной российский спортсмен отказаться учас...
4,4,Байден и Си Цзиньпин обсудили ситуацию вокруг ...,Политика,байден и си цзиньпин обсудили ситуацию вокруг ...,байден и си цзиньпин обсудили ситуацию вокруг ...,байден си цзиньпин обсудили ситуацию вокруг ti...,байден си цзиньпин обсудили ситуацию вокруг ti...,байден си цзиньпин обсудили ситуацию вокруг ti...,байден си цзиньпин обсудили ситуацию вокруг ti...,"['байден', 'си', 'цзиньпин', 'обсудили', 'ситу...",байден си цзиньпин обсудить ситуация вокруг ti...,байден си цзиньпин обсудить ситуация вокруг ti...

In [8]:
from bertopic import BERTopic
import pandas as pd
import nltk
nltk.download('stopwords')
#from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [9]:
df.head(16616)

,Unnamed: 0,title,tags,text_lower,text_punct,text_stop,text_common,text_rare,text_nonum,text_token,text_lemm,text_ready
0,0,В Курской области объявили опасность атаки БПЛА,Происшествия,в курской области объявили опасность атаки бпла,в курской области объявили опасность атаки бпла,курской области объявили опасность атаки бпла,курской объявили опасность атаки бпла,курской объявили опасность атаки бпла,курской объявили опасность атаки бпла,"['курской', 'объявили', 'опасность', 'атаки', ...",курский объявить опасность атака бпнуть,курский область объявить опасность атака бпнуть
1,1,Юристы прокомментировали иск пострадавших в от...,Следствие и суд,юристы прокомментировали иск пострадавших в от...,юристы прокомментировали иск пострадавших в от...,юристы прокомментировали иск пострадавших отно...,юристы прокомментировали иск пострадавших отно...,юристы прокомментировали иск пострадавших отно...,юристы прокомментировали иск пострадавших отно...,"['юристы', 'прокомментировали', 'иск', 'постра...",юрист прокомментировать иск пострадать отношен...,юрист прокомментировать иск пострадать отношен...
2,2,На Западе рассказали о нехватке Patriot для пе...,Политика,на западе рассказали о нехватке patriot для пе...,на западе рассказали о нехватке patriot для пе...,западе рассказали нехватке patriot передачи всу,западе нехватке patriot передачи,западе нехватке patriot передачи,западе нехватке patriot передачи,"['западе', 'нехватке', 'patriot', 'передачи']",запад нехватка patriot передача,запад рассказать нехватка patriot передача всу
3,3,Очередные российские спортсмены отказались от ...,Летние виды,очередные российские спортсмены отказались от ...,очередные российские спортсмены отказались от ...,очередные российские спортсмены отказались уча...,очередные спортсмены отказались участия олимпиаде,очередные спортсмены отказались участия олимпиаде,очередные спортсмены отказались участия олимпиаде,"['очередные', 'спортсмены', 'отказались', 'уча...",очередной спортсмен отказаться участие олимпиада,очередной российский спортсмен отказаться учас...
4,4,Байден и Си Цзиньпин обсудили ситуацию вокруг ...,Политика,байден и си цзиньпин обсудили ситуацию вокруг ...,байден и си цзиньпин обсудили ситуацию вокруг ...,байден си цзиньпин обсудили ситуацию вокруг ti...,байден си цзиньпин обсудили ситуацию вокруг ti...,байден си цзиньпин обсудили ситуацию вокруг ti...,байден си цзиньпин обсудили ситуацию вокруг ti...,"['байден', 'си', 'цзиньпин', 'обсудили', 'ситу...",байден си цзиньпин обсудить ситуация вокруг ti...,байден си цзиньпин обсудить ситуация вокруг ti...
...,...,...,...,...,...,...,...,...,...,...,...,...
16611,16611,Безруков пожаловался на говоривших голосом Хаб...,Кино,безруков пожаловался на говоривших голосом хаб...,безруков пожаловался на говоривших голосом хаб...,безруков пожаловался говоривших голосом хабенс...,безруков пожаловался говоривших голосом хабенс...,безруков пожаловался говоривших голосом хабенс...,безруков пожаловался говоривших голосом хабенс...,"['безруков', 'пожаловался', 'говоривших', 'гол...",безруков пожаловаться говорить голос хабенский...,безруков пожаловаться говорить голос хабенский...
16612,16612,Генсек НАТО поздравил Швецию с ратификацией ее...,Политика,генсек нато поздравил швецию с ратификацией ее...,генсек нато поздравил швецию с ратификацией ее...,генсек нато поздравил швецию ратификацией заяв...,генсек поздравил швецию ратификацией заявки ве...,генсек поздравил швецию ратификацией заявки ве...,генсек поздравил швецию ратификацией заявки ве...,"['генсек', 'поздравил', 'швецию', 'ратификацие...",генсек поздравить швеция ратификация заявка ве...,генсек нато поздравить швеция ратификация заяв...
16613,16613,Детей завалило песком во время игры на пляже,Люди,детей завалило песком во время игры на пляже,детей завалило песком во время игры на пляже,детей завалило песком время игры пляже,детей завалило песком время игры пляже,детей завалило песком время игры пляже,детей завалило песком время игры пляже,"['детей', 'завалило', 'песком', 'время', 'игры...",ребёнок завалить песок время игра пляж,ребёнок завалить песок время игра пляж
16614,16614,Перечислены простые способы спастись от гайморита,Уход за собой,перечислены простые способы спастись от гайморита,перечислены простые способы спастись от гайморита,перечислены простые способы спастись гайморита,перечислены простые способы спастись гайморита,перечислены простые способы спастись гайморита,перечислены простые способы спастись гайморита,"['перечислены', 'простые', 'способы', 'спастис...",перечислить простой способ спастись гайморит,перечислить простой способ спастись гайморит
16615,16615,Глава Генштаба посетил командный пункт в зоне СВО,Политика,глава генштаба посетил командный пункт в зоне сво,глава генштаба посетил командный пункт в зоне сво,глава генштаба посетил командный пункт зоне сво,генштаба посетил командный пункт зоне,генштаба посетил командный пункт зоне,генштаба посетил командный пункт зоне,"['генштаба', 'посетил', 'командный', 'пункт', ...",генштаб посетить командный пункт зона,глава генштаб посетить командный пункт зона сво

In [10]:
docs

['курский область объявить опасность атака бпнуть',
 'юрист прокомментировать иск пострадать отношение владелец крокус',
 'запад рассказать нехватка patriot передача всу',
 'очередной российский спортсмен отказаться участие олимпиада 2024',
 'байден си цзиньпин обсудить ситуация вокруг tiktok',
 'последствие мощный землетрясение тайвань показать видео',
 'родственник погибнуть крокус назначить 66 пенсия',
 'цунами достигнуть японский остров землетрясение близ тайвань',
 'украина заявить ужесточение мобилизация из за военный закон',
 'британия осудить северный корея из за пуск баллистический ракета',
 'ростов выйти следующий этап кубок россия',
 'локомотив повести серия трактор полуфинал кубок гагарин',
 'назвать число россиянин кредит',
 'запад создать план сохранение поставка оружие украина возвращение трамп',
 'близ тайвань зафиксировать четыре землетрясение',
 'диетолог раскрыть неожиданный польза апельсин',
 'украинский миллиардер стать бедный',
 'крупный производитель чип эвакуировать завод тайвань',
 'мвд отказаться ограничивать пребывание получить внж мигрант',
 'запад рассказать печальный судьба харьков',
 'бывший учительница дать 12 год тюрьма изнасилование ученица секс игрушка',
 'сша заявить нежелание вашингтон вступать прямой столкновение россия',
 'минобороны заявить увеличение число желать служить контракт москва',
 'тайвань восемь человек оказаться заблокировать частично обрушиться дом',
 'невеста тайно сшить свадебный платье удивить жених результат',
 'умереть самый старый мужчина мир кто быть называть самый важный жизнь удаться дожить 114 год',
 'россиянин забить смерть мужчина время ссора улица',
 'минобороны рассказать отношение россиянин служба теракт крокус',
 'овечкин стать второй список хороший ассистент нхл среди россиянин',
 'зарубежный эксперт указать быстрый уничтожение западный оружие украина',
 'мужчина обсудить главный скрывать жена тайна',
 'запад заявить беспокойство ряд всу из за решение российский генерал',
 'турецкий город выборы захлестнуть протест стрельба',
 'скр заняться расследование преступление всу против житель белгородский область',
 'российский самолёт экстренно сесть друг место из за больной пассажир',
 'россиянин войти топ 10 любитель импортный алкоголь',
 'россиянин похитить увезти лес требование заплатить 200 миллион рубль',
 'мужчина заняться секс женщина мечта сильно удивиться',
 'малкин отметиться дубль передача принести питтсбург победа матч нхл',
 'российский войско продвинуться три направление зона спецоперация',
 'доцент петербургский университет аватарка флаг украина задержать',
 'пострадать атака беспилотник татарстан оказаться гражданин страна',
 'администрация байден призвать конгресс продать истребитель 15 израиль',
 'мид россия отреагировать участие шведский наёмник бой сторона всу',
 'урал таксист реанимировать поездка 25 летний девушка приступ эпилепсия',
 'раскрыть стоимость отпуск ксения собчак один самый дорогой отель дубай',
 'пытаться уехать украина россиянин признать виновный госизмена осудить',
 'головин войти тройка самый дорогой игрок страна бывший ссср',
 '21 летний россиянин обвинить реабилитация нацизм из за выложить видео',
 'сосед кузьминов исключить украинский след кончина',
 'российский регион два школьница задержать сообщение теракт',
 'военный эксперт рассказать особенность стратегия россия зона сво',
 'командир ахмат рассказать просьба боец всу российский гражданство',
 'британия призвать нато закупать снаряд украина',
 'россиянин предупредить штраф недопуск квартира газовщик',
 'раскрыть причина аномальный град',
 'байден трамп выйти лидер праймериз нью йорк',
 'назвать главный причина осложнение пластический операция',
 'тайвань мощный землетрясение обрушиться здание завод',
 'очевидец рассказать допрос сосед российский лётчик перебежчик',
 'россиянин дать совет покупка валюта',
 'назвать особенность атаковать елабуга дрон',
 'полицейский применить табельный оружие остановка авто пьяный россиянин',
 'мэр харьков заявить разработка план эвакуация город',
 'майк тайсон назвать самый приятный момент карьера',
 'российский прокурор объяснить изъятие акция частный инвестор',
 'рекордный продажа новый легковушка россия объяснить',
 'родственник жертва теракт крокус назначить 66 пенсия',
 'назвать простой способ убрать запах еда пластиковый контейнер',
 'самый старый мужчина мир скончаться возраст 114 год',
 'генпрокуратура запросить сша европа дать расследование теракт россия',
 'крупный водочный завод россия сменить владелец',
 'рита ор появиться публика бюстгальтер',
 'раскрыть эффективность fpv дрон термокамера против бронетехника всу',
 'петербурженка избить ремень десятилетний дочь полусмерть',
 'россия третьеклассник сломать рука мальчик посоветовать мама угомониться',
 'грузия вернуться рассмотрение скандальный закон иноагент',
 'увеличиться число жертва среди ребёнок теракт крокус',
 'стать известно атака всу крупный агрокомплекс россия',
 'малкин признать первый звезда день нхл',
 'елена летучий выйти свет кружевной бюстгальтер',
 'сша забеспокоиться из за принять киргизия закон',
 'минобороны россия рассказать сдаться плен гарнизон опорный пункт всу',
 'глава мид три страна европа призвать устранить насущный проблема нато',
 'подложить газовый баллон рельс россиянин обвинить теракт',
 'франция назвать условие поражение украина',
 'фигурант обжаловать свой арест дело теракт крокус',
 'рособрнадзор ответить дать использование текст алексиевич егэ',
 'украина вновь открыться zara bershk',
 'российский снайпер победить дуэль два солдат всу',
 'певица тейлор свифт стать долларовый миллиардерша',
 'финалист голос избить москва',
 'назвать преимущество российский джокер 10',
 'общественный деятель скобова задержать оправдание терроризм',
 'число пострадать первый начало сво атака бпнуть татарстан снова вырасти',
 'парламент петербург перекличка начать упоминание новый иноагент',
 'россиянин предупредить риска опасный психический состояние из за стресс',
 'мать один фигурант дело теракт крокус назвать случиться горе',
 'матвиенко высказаться наказание террорист крокус',
 'обнаружить новый быстро вращаться пульсар',
 'основатель крупный россия производитель краска осудить заочно хищение',
 'вероятность дефолт турция оценить',
 'кремль объяснить рост число желать пойти служба контракт',
 'совбез заявить украинский след теракт крокус',
 'вероятность уход apple европейский рынок оценить',
 'украинский дрон наслать скрытый радиомаяк помощь всу определять позиция российский военный',
 'мишустин заявить рекордный показатель продолжительность жизнь',
 'запад признать семикратное превосходство россия снаряд украина',
 'канада призвать игнорировать россиянин олимпийский игра 2024',
 'москва побить рекорд тепло',
 'назвать последствие землетрясение тайвань',
 'последствие землетрясение тайвань попасть видео',
 'песок ответить вопрос передача сша данные возможность теракт крокус',
 'двое мужчина украсть россиянка сумка семья миллион рубль попасть видео',
 'информация критический урон нпз нижнекамск найти подтверждение',
 'центробанк сократить продажа валюта рынок',
 'культовый платье мэрилин монро продать аукцион 30 миллион рубль',
 'рост цена турция ускориться',
 'отряд шиит заявить свой атака израильский аэропорт',
 'пластический хирург объяснить последний изменение внешность ким кардашьян',
 'песок анонсировать встреча путин вкс глава два российский регион',
 'обнаружить новый способ борьба болезнь альцгеймер',
 'российский депутат заседание посмотреть видео приключение унитаз',
 'россия нарастить ввоз рыба морепродукт',
 'бывший гендиректор спартак стать новый исполнительный директор рпл',
 'макрон отказаться помощь сша столкновение россия украина',
 'диетолог указать вредный обезжиренный продукт',
 'назвать снижать воспаление организм продукт',
 'россиянин задержать кража 20 миллион рубль 2017 год',
 'медведчук указать нужда зеленский',
 'россиянин захотеть снять ребёнок самокат',
 'россиянин раскрыть стоимость бюджетный отдых сочи',
 'назвать число остаться сирота теракт крокус ребёнок',
 'большинство страна нато поддержать кандидатура новый генсек',
 'московский аэропорт изменить схема заход посадка',
 'стать известно обрушение потолок один московский школа',
 'польша отказаться поддержать кандидатура фаворит пост генсек нато',
 'ребёнок пострадать обрушение потолок московский школа',
 'нефть показать московский кинотеатр',
 'сша израиль разойтись ключевой вопрос газа',
 'российский бармен осудить госизмена попытка теракт',
 'крымский спортсмен отказаться ехать олимпийский игра',
 '13 летний девочка выстрелить лицо 11 летний брат время игра',
 'пегов лавроненко стать народный артист',
 'учёный рассказать прирождённый геймер',
 'путин присвоить звание герой россия член экипаж crew dragon',
 'мид увидеть след вашингтон ужесточение мобилизация украина',
 'российский регион загореться предприятие выпуск забор',
 'подмосковье дверной глазок выстрелить уроженец дагестан',
 'мишустин заявить устраивать результат борьба рост цена',
 'посол израиль заявить нахождение заложник хамас трое гражданин россия',
 'гигантский змея наслать подземелье российский город',
 'звезда comedy woman назвать нравиться муж итальянец черта русский',
 'глава филиал дагэнерго заподозрить хищение миллиард рубль',
 '63 летний священник взять жена 12 летний девочка',
 'задержать дагестан боевик арестовать месяц',
 'сша обвинить попытка нанести урон россия затягивание конфликт украина',
 'новый москвич оказаться дорогой прошлогодний',
 'власть сообщить неоднократный атака посёлок белгородский область',
 'москвичка пожаловаться мешать спать стук найти козырёк дом',
 'запад обеспокоиться скорый прорыв оборона украина',
 'мишустин рассказать рост экономика россия',
 'назвать причина появление кашель ночь',
 'москва строитель упасть шахта лифт',
 'мишустин назвать задача налоговый реформа россия',
 'бывший тренер киевский динамо избить польша',
 'мишустин понадеяться мощный инвестиция бизнес',
 'упавший ограждение придавить мужчина москва',
 'нато захотеть сделать помощь украина предсказуемый',
 'мид россия прокомментировать перестановка руководство украина',
 'женщина поймать крупный рыба побить 18 летний рекорд',
 'белгород назвать один самый благоприятный город жизнь россия',
 'никита ефрем рассказать тоска отец',
 'мишустин заявить снижение сырьевой зависимость россия',
 'россия захотеть проверить ведущий лазарев оправдание терроризм',
 'президент финляндия приехать киев заключить соглашение безопасность',
 'назвать срок возможный обрушение фронт всу',
 'бывший жена петросян подать суд из за наследство',
 'армия россия занять выгодный рубеж один направление зона сво',
 'киев опровергнуть использование иностранный оружие удар нпз татарстан',
 'взрывоопасный предмет наслать неподалёку белгородский село',
 'раскрыть неочевидный способ лёгкий пережить аллергия',
 'польша указать превосходство финансовый помощь ес украина сша',
 'москва начать бегать туалет',
 'мид россия проследить реакция ряд страна запрос теракт',
 'дагестанский учитель музыка избить запугать начальник попасть видео',
 'европа замедлиться инфляция',
 'россия обратить внимание пугать ответ умный колонка героиня мультфильм',
 'уровень российский госдолг назвать безопасный',
 'финляндия предложить закрыть граница россия до дальнейший уведомление',
 'лететь чита пассажирский самолёт резко сменить курс сесть друг место',
 'финляндия отправить украина очередной пакет военный помощь 188 миллион евро',
 'нато заявить наращивание военный мощь россия',
 'любитель кофе предупредить возможный опасность организм',
 'россиянин признаться желание отдыхать работа',
 'россиянин предупредить угрожать краснодарский край опасность',
 'раскрыть подробность обыск участие собразец российский it компания',
 'бали пьяный россиянин попасть авария авто французский турист',
 'ведущий первый канал раскрыть подробность работа эрнст',
 'володин отчитать депутат госдума поведение время доклад правительство',
 'китай обвинить попытка подкупить мальдивы 1500 тонна питьевой вода',
 'украина решить переименовать село ватутиный залужной',
 'российский подросток задержать подозрение расправа незнакомый мужчина',
 'экс супруг фёдор бондарчук заметить сумка миллион рубль',
 'военный эксперт высказаться ответ россия действие финляндия нато',
 'россиянин назвать самый импортозамещенный отрасль',
 'украинский боевик осудить приказ обстрелять жилой дом днр миномёт',
 'бузов обделить внимание покусать официантка кологривый',
 'отец марин ле пен поместить опека из за ухудшение здоровье',
 'россиянин получить 13 год колония двойной расправа частный лофт',
 'цска победить балтика матч кубок россия',
 'украина заявить препятствование зеленский повышение призывный возраст',
 'поляк удивляться бобёр обзывать курва это стать мем покорить весь мир',
 'украина заявить необходимость потратить госдолг триллион гривна',
 'песок прокомментировать слово зеленский мобилизация россия',
 'путин предложить бизнесмен земля из под забросить свалка',
 'подмосковье разлиться море',
 'американский экономист назвать клоун инициатор изъятие российский актив',
 'апрель праздник сегодня отмечать россия мир',
 'объяснить провал натовский bayraktar switchblade зона сво',
 'назвать малоизвестный признак рак кишечник',
 'ростов на дон шимпанзе открыть талант художник',
 'полковник назвать способ борьба против дрон всу маяк ловушка',
 'байден впервые долгий время обойти трамп опрос',
 'шойгу предупредить франция последствие отправка контингент украина',
 'россиянин стать брать вдвое автокредит',
 'блинкен опоздать встреча глава мид страна нато из за сломать самолёт',
 'врач российский психдиспансер отказаться отдавать восьмилетний пациент',
 'глава минобороны франция поговорить шойгу',
 'раскрыть настоящий отношение мужчина оральный секс',
 'верховный лидер иран иврит обратиться израиль угроза',
 'робби уильямс рассказать интерес сторона пришелец',
 '56 летний крестница король карла iii сняться топлёс отдых',
 'трое мужчина смерть забить россиянин центр луганск',
 'стать известно возможный размещение японский войско филиппины',
 'кучер установить рекорд нхл',
 'министр страна нато закатить глаз предложение столтенберг украина',
 'прохожий найти снаряд рпг строительный площадка москва',
 'украина получить миллион евро финляндия',
 'россиянин вытащить багаж украшение 400 тысяча рубль рейс турция',
 'счётный палата высказаться состояние госдолг россия',
 'назвать переломный момент сво битва донбасс',
 'каждый третий россиянин предпочесть отечественный автомобиль иномарка',
 'мастер участок путь ярославский область арестовать дтп поезд автобус',
 'бывший российский хакер раскрыть условие жизнь тюрьма сша',
 'олимпийский чемпионка сотникова объявить помолвка',
 'словакия заявить возможный катастрофа из за вооружение украина',
 'раскрыть долговременный угроза здоровье из за курение',
 'генсек нато осудить удар израиль гумконвой',
 'силовик нагрянуть обыск российский it компания это связать украинский хакер',
 'россиянка бюджетный отдохнуть мальдивы поделиться впечатление',
 'калашников представить скат ночной аэрофотосъёмка',
 'подполье сообщить нашествие иностранный наёмник харьков',
 'монтёр путь арестовать дтп автобус поезд ярославский область',
 'росгвардия представить трофейный оружие экстехнострадкий',
 'такер карлсон рассказать необъявленный война сша против россия',
 'прохожий отрезать рука запретить курить владелец винный магазин',
 'дело халатность завести дтп автобус поезд ярославский область',
 'кирстен данст рассказать намерение продюсер насильно исправить зуб',
 'сша назвать имя виновник начало конфликт украина',
 'украина назвать диверсия проект ужесточение мобилизация',
 'крым предложить ужесточить наказание разжигание рознь',
 'титановый барс представить выставка экспотехностража',
 'россиянин рассказать способ обезопасить сезон клещ',
 'блинкен рассказать алиев встреча ес армения сша',
 'назвать преимущество недостаток китайский автомобиль',
 'россия спрогнозировать срок действие санкция запад',
 'глава мид украина венгрия провести встреча брюссель',
 'мишустин назвать дата пересдача один предмет егэ',
 'москвич раскрыть стоимость сам старый квартира город',
 'похолодание минус 23 предречь два российский регион',
 'раскрыть способ справиться неприятный тревожить женщина симптом',
 'назвать способ восстановить сексуальный отношение ссора',
 'хёрш рассказать американский предупреждение теракт крокус',
 'россия опровергнуть заявление сша предупреждение теракт крокус',
 'мишустин предложить подумать справедливый перераспределение прибыль банк',
 'россия вырасти число природный катаклизм',
 'теракт крокус причастность запад украинский след говорить шойгу министр оборона франция',
 'шойгу заявить необходимость довести конец расследование теракт',
 'русало рассказать создание департамент промышленный ия',
 'россиянин притвориться 15 летний школьница ради голый фото подросток',
 'известный российский актриса показать фото штаны',
 'парень бросить жаловаться головной боль возлюбить из за один просьба',
 'шойгу счесть бессмысленный переговоры украина участие россия',
 'конвоир передать телефон главарь опг шишкануть прямой кишка подручный',
 'россиянин назвать продукт защита зрение',
 'президент грузия увидеть саботаж действие пророссийский правительство',
 'мид назвать заявление макрон отправка войско украина недопустимый',
 'популярный российский комик рассказать колхозник концерт граница',
 'камчатка осудить фигурант дело растрата кроноцкий заповедник',
 'россия запустить серийный производство грань',
 'корвет резкий отразить воздушный нападение противник',
 '104 летний мужчина назвать хороший продукт долголетие',
 'модель victoria secret приспустить бикини фото отдых',
 'спикер рада назвать срок рассмотрение закон мобилизация',
 'первый пациент пересадить почка свинья выписать больница',
 'мегана фокс кардинально сменить имидж показать результат фанат',
 'очевидец сообщить громкий хлопок мощный пожар ростов на дон',
 'билайн представить фильм расследование рынок серый sim карта',
 'аналитик спрогнозировать изменение ядерный доктрина россия',
 'счёт лечение больница сша возмутить пользователь сеть',
 'пентагон выразить израиль возмущение удар гумконвой',
 'путин дать поручение оказание помощь человек зона паводковый',
 'россиянка назвать самый модный цвет одежда весна лето',
 'украина решить переименовать находиться контроль россия город',
 'минобороны заявить перехват дрон белгородский тульский область',
 'самый сексуальный мир волейболистка показать видео крошечный бикини',
 'фас заподозрить apple нарушение антимонопольный законодательство',
 'назвать самый разбогатеть год российский миллиардер',
 'россия модернизировать нива сво',
 'бывший министр финансы фрг рассказать попытка свергнуть меркель 2015 год',
 'белгородский область назвать число отказаться уезжать житель грайворон',
 'мвд объяснить очередь гаи москва',
 'рогов призвать нато тешить иллюзия насчёт украинский конфликт',
 'россиянин назвать способ научиться радоваться понедельник',
 'алиев заявить отсутствие план нападать армения',
 'глава минобороны франция отвергнуть связь теракт крокус украина',
 'идея строительство мост сахалин оценить',
 'мид напомнить нато последствие угроза безопасность россия',
 'россиянка родить дом дочь задушить один цель',
 'собянин рассказать устранение последствие непогода москва',
 'российский военный поразить место сборка хранение беспилотник всу',
 'конгрессвумен обвинить сша приближение мировой война',
 'россия уровень безработица снизиться исторический минимум',
 'мид нидерланды высказаться создание фонд нато украина',
 'франция заявить неготовность париж диалог москва',
 'аэрофлот рассказать оказание помощь пассажир время рейс',
 'омбудсмен опровергнуть причастность задержать москва чеченец крокус',
 'лидер немецкий партия заподозрить свой депутат связь россия',
 'подросток ради новый кроссовок обмануть пенсионерка полмиллиона рубль',
 'россия увеличить выпуск бронетанковый вооружение',
 'часть россиянин предупредить возвращение зима',

In [11]:
from nltk.corpus import stopwords

In [12]:
# Remove stopwords **after** generating the clusters
# NOTE: You can also perform the lemmatization here
my_stopwords = stopwords.words("russian")
vectorizer_model = CountVectorizer(stop_words=my_stopwords)

In [13]:
#from hdbscan import HDBSCAN
documents = df['text_ready'].astype(str).values.tolist()
umap_model = UMAP(n_neighbors=10, n_components=3,
                  min_dist=0.0, metric='cosine', random_state=13)

In [14]:


# Load KBLab's Swedish sentence transformer model
sentence_model = SentenceTransformer("paraphrase-multilingual-mpnet-base-v2", device="cuda")

# Initialize BERTopic with the settings we want
topic_model = BERTopic(embedding_model=sentence_model,
                       vectorizer_model=vectorizer_model,
                       umap_model=umap_model,
                       calculate_probabilities=True,
                       verbose=True)

topic_model.save("drive/MyDrive/lenta_model", serialization="pickle")
# Fit the model
#topics, probs = topic_model.fit_transform(documents)

2024-12-07 09:03:20,784 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

In [15]:
# Fit the model
topics, probs = topic_model.fit_transform(documents)

2024-12-07 09:03:28,233 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/2157 [00:00<?, ?it/s]

2024-12-07 09:04:53,923 - BERTopic - Embedding - Completed ✓
2024-12-07 09:04:53,925 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-12-07 09:06:28,406 - BERTopic - Dimensionality - Completed ✓
2024-12-07 09:06:28,408 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-12-07 10:32:14,768 - BERTopic - Cluster - Completed ✓
2024-12-07 10:32:14,794 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-12-07 10:32:16,286 - BERTopic - Representation - Completed ✓

In [16]:
while True:
    pass

KeyboardInterrupt:

In [17]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,25003,-1_москва_город_всу_дело,"[москва, город, всу, дело, сво, попасть, видео...",[военный эксперт назвать возможный срок операц...
1,0,1276,0_конфликт_украина_patriot_запад,"[конфликт, украина, patriot, запад, завершение...",[захаров предупредить сша риска из за поставка...
2,1,516,1_полицейский_суд_арестовать_судья,"[полицейский, суд, арестовать, судья, арест, в...","[мужчина нож напасть российский полицейский, с..."
3,2,470,2_авиакомпания_рейс_самолёт_аэропорт,"[авиакомпания, рейс, самолёт, аэропорт, полёт,...",[пять международный авиакомпания отменить рейс...
4,3,390,3_зеленский_залужный_офис_формула,"[зеленский, залужный, офис, формула, встреча, ...",[залужный прокомментировать разговор зеленский...
...,...,...,...,...,...
813,812,10,812_жертва_550_папуа_избирком,"[жертва, 550, папуа, избирком, увеличиться, гв...","[увеличиться количество жертва теракт крокус, ..."
814,813,10,813_полковник_тактика_генерал_супероружие,"[полковник, тактика, генерал, супероружие, сур...",[генерал всу заявить смена тактика российский ...
815,814,10,814_ядерный_арсенал_китай_боеголовка,"[ядерный, арсенал, китай, боеголовка, порог, м...",[сша допустить отставание китай число ядерный ...
816,815,10,815_левша_барс_шлем_ка,"[левша, барс, шлем, ка, промышленность, натовс...",[ран сотрудничать национальный академия четыре...
817,816,10,816_спутник_группировка_дзз_к2,"[спутник, группировка, дзз, к2, глонасс, запус...","[россия перенести запуск спутник экспресс, ста..."

In [18]:
topic_model.get_topic(0)

[('конфликт', 0.015172846947149448),
 ('украина', 0.009338568722134228),
 ('patriot', 0.008944376194611319),
 ('запад', 0.006034054854434247),
 ('завершение', 0.005879901251972224),
 ('украинец', 0.005830997015733302),
 ('киев', 0.005754700463025255),
 ('вступление', 0.005530602892475148),
 ('потеря', 0.005496815910868003),
 ('нато', 0.0048575615518353455)]

In [19]:
topic_model.get_representative_docs(0)

['захаров предупредить сша риска из за поставка украина система пво patriot',
 'трамп назвать условие завершение конфликт украина',
 'сша назвать условие поставка patriot украина']

In [20]:
topic_model.get_topic(4) # topic_model.get_topic(similar_topics[0])

[('беспилотник', 0.050484605896433145),
 ('дрон', 0.04648640926922218),
 ('сбить', 0.020986202506033034),
 ('брянский', 0.01995338025065552),
 ('область', 0.01729538323193954),
 ('атаковать', 0.01688745432565012),
 ('белгородский', 0.01621614770478666),
 ('атака', 0.014997914216955994),
 ('нефтебаза', 0.01409358927974908),
 ('курский', 0.013388103188178685)]

In [23]:
topic_model.visualize_topics()

In [21]:
fig = topic_model.visualize_topics()
fig.write_html("/content/sample_data/lenta_topics.html")

In [22]:
topic_model.visualize_hierarchy()

In [24]:
hierarchical_topics = topic_model.hierarchical_topics(documents)
topic_model.visualize_hierarchy(hierarchical_topics=hierarchical_topics)

100%|██████████| 816/816 [00:05<00:00, 162.01it/s]

In [25]:
topic_model.reduce_topics(docs, nr_topics=20)

2024-12-07 10:34:13,520 - BERTopic - Topic reduction - Reducing number of topics
2024-12-07 10:34:14,357 - BERTopic - Topic reduction - Reduced number of topics from 818 to 20

In [26]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,25003,-1_россия_российский_украина_назвать,"[россия, российский, украина, назвать, россиян...","[сша заявить подготовка польша война россия, с..."
1,0,26122,0_украина_россия_российский_россиянин,"[украина, россия, российский, россиянин, заяви...",[глава граничить украина российский регион соо...
2,1,8449,1_израиль_всу_сша_назвать,"[израиль, всу, сша, назвать, заявить, жильё, а...",[британия призвать напасть иран случай удар из...
3,2,3543,2_летний_назвать_способ_женщина,"[летний, назвать, способ, женщина, врач, показ...",[51 летний модель показать фигура красный купа...
4,3,1084,3_журналист_блогерш_блогер_youtube,"[журналист, блогерш, блогер, youtube, twitter,...","[российский журналист попасть обстрел донбасс,..."
5,4,1042,4_китай_корея_южный_таиланд,"[китай, корея, южный, таиланд, китайский, сша,...","[назвать перспектива отношение тайвань китай, ..."
6,5,879,5_коронавирус_covid_19_рак,"[коронавирус, covid, 19, рак, омикрон, грипп, ...",[россия выявить десятка случай заражение новый...
7,6,851,6_медведев_медведь_обезьяна_оспа,"[медведев, медведь, обезьяна, оспа, акула, роб...",[медведев прокомментировать условие британия п...
8,7,582,7_ипотека_доллар_ставка_криптовалюта,"[ипотека, доллар, ставка, криптовалюта, пенсия...","[госдума назвать льготный ипотека ошибка, сбер..."
9,8,405,8_apple_iphone_смартфон_samsung,"[apple, iphone, смартфон, samsung, android, ск...","[apple увеличить производство iphone 14, apple..."
10,9,345,9_автобус_tesla_дтп_таксист,"[автобус, tesla, дтп, таксист, водитель, такси...",[дтп автобус российский регион пострадать 15 ч...
11,10,288,10_иран_дагестан_талиб_таджикистан,"[иран, дагестан, талиб, таджикистан, афганиста...",[лавров заявить отсутствие ядерный оружие иран...
12,11,129,11_windows_microsoft_11_playstation,"[windows, microsoft, 11, playstation, обновлен...","[windows 11 сделать похожий windows 10, micros..."
13,12,67,12_землетрясение_произойти_тайвань_мощный,"[землетрясение, произойти, тайвань, мощный, яп...","[российский регион произойти землетрясение, зе..."
14,13,56,13_эквадор_аргентина_банан_президент,"[эквадор, аргентина, банан, президент, беспоря...","[влияние мятеж эквадор поставка банан оценить,..."
15,14,53,14_лотерея_миллионер_миллиардер_выиграть,"[лотерея, миллионер, миллиардер, выиграть, ста...",[экс ведущий кто хотеть стать миллионер расска...
16,15,41,15_whatsapp_функция_появиться_новый,"[whatsapp, функция, появиться, новый, пользова...","[whatsapp появиться новый функция, whatsapp по..."
17,16,28,16_макдоналдс_преемник_рецепт_название,"[макдоналдс, преемник, рецепт, название, ресто...","[володин найти замена макдоналдс россия, преем..."
18,17,21,17_поздравить_победа_выборы_путин,"[поздравить, победа, выборы, путин, президент,...",[путин поздравить новый президент мексика побе...
19,18,13,18_австралия_australian_джокович_open,"[австралия, australian, джокович, open, ассанж...","[ассанж прибыть австралия, джокович выдать виз..."

In [27]:
topic_model.get_topic(3)

[('журналист', 0.10100323448989688),
 ('блогерш', 0.07869922968372589),
 ('блогер', 0.07636527018065685),
 ('youtube', 0.04467010976619872),
 ('twitter', 0.03996798126247909),
 ('google', 0.03508179184434601),
 ('популярный', 0.03269055204600515),
 ('российский', 0.031578384142788504),
 ('журналистка', 0.030707751586051282),
 ('сбер', 0.030168903417721125)]

In [28]:
topic_model.visualize_topics()

In [32]:
fig4 = topic_model.visualize_barchart(width=280, height=330,top_n_topics=20, n_words=20)
topic_model.visualize_barchart(width=280, height=330,top_n_topics=20, n_words=20)

In [35]:
fig4.write_html("/content/drive/MyDrive/lenta_topic_20wordBars.html")

In [37]:
fig5 = topic_model.visualize_heatmap(n_clusters=9)
topic_model.visualize_heatmap(n_clusters=9)
fig5.write_html("/content/sample_data/lenta_topic_20corr.html")